/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Sat Oct 24 15:16:33 2009
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "OBR" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_OBR_public_data[] = {'3', '0', '8', '1', '9', 'D',
                                               '3', '0', '0', 'D', '0', '6',
                                               '0', '9', '2', 'A', '8', '6',
                                               '4', '8', '8', '6', 'F', '7',
                                               '0', 'D', '0', '1', '0', '1',
                                               '0', '1', '0', '5', '0', '0',
                                               '0', '3', '8', '1', '8', 'B',
                                               '0', '0', '3', '0', '8', '1',
                                               '8', '7', '0', '2', '8', '1',
                                               '8', '1', '0', '0', 'C', '4',
                                               '9', 'C', 'A', 'C', '3', '4',
                                               'E', 'D', '1', '3', 'A', '5',
                                               '2', '0', '6', '5', '8', 'F',
                                               '6', 'F', '8', 'E', '0', '1',
                                               '3', '8', 'C', '4', '3', '1',
                                               '5', 'B', '4', '3', '1', '5',
                                               '2', '7', '7', 'E', 'D', '3',
                                               'F', '7', 'D', 'A', 'E', '5',
                                               '3', '0', '9', '9', 'D', 'B',
                                               '0', '8', 'E', 'E', '5', '8',
                                               '9', 'F', '8', '0', '4', 'D',
                                               '4', 'B', '9', '8', '1', '3',
                                               '2', '6', 'A', '5', '2', 'C',
                                               'C', 'E', '4', '3', '8', '2',
                                               'E', '9', 'F', '2', 'B', '4',
                                               'D', '0', '8', '5', 'E', 'B',
                                               '9', '5', '0', 'C', '7', 'A',
                                               'B', '1', '2', 'E', 'D', 'E',
                                               '2', 'D', '4', '1', '2', '9',
                                               '7', '8', '2', '0', 'E', '6',
                                               '3', '7', '7', 'A', '5', 'F',
                                               'E', 'B', '5', '6', '8', '9',
                                               'D', '4', 'E', '6', '0', '3',
                                               '2', 'F', '6', '0', 'C', '4',
                                               '3', '0', '7', '4', 'A', '0',
                                               '4', 'C', '2', '6', 'A', 'B',
                                               '7', '2', 'F', '5', '4', 'B',
                                               '5', '1', 'B', 'B', '4', '6',
                                               '0', '5', '7', '8', '7', '8',
                                               '5', 'B', '1', '9', '9', '0',
                                               '1', '4', '3', '1', '4', 'A',
                                               '6', '5', 'F', '0', '9', '0',
                                               'B', '6', '1', 'F', 'C', '2',
                                               '0', '1', '6', '9', '4', '5',
                                               '3', 'B', '5', '8', 'F', 'C',
                                               '8', 'B', 'A', '4', '3', 'E',
                                               '6', '7', '7', '6', 'E', 'B',
                                               '7', 'E', 'C', 'D', '3', '1',
                                               '7', '8', 'B', '5', '6', 'A',
                                               'B', '0', 'F', 'A', '0', '6',
                                               'D', 'D', '6', '4', '9', '6',
                                               '7', 'C', 'B', '1', '4', '9',
                                               'E', '5', '0', '2', '0', '1',
                                               '1', '1', '\0'};

const char *__MCC_OBR_name_data = "OBR";

const char *__MCC_OBR_root_data = "";

const unsigned char __MCC_OBR_session_data[] = {'9', '2', 'C', '7', '9', '7',
                                                '7', '5', '0', 'B', '1', '0',
                                                '1', '2', '8', '9', '7', '5',
                                                '5', 'E', 'C', 'A', '0', 'D',
                                                '7', 'C', '5', 'B', '8', '7',
                                                '6', '3', '7', '9', '4', '0',
                                                'D', 'A', '4', '0', '1', '8',
                                                '7', '8', '2', '9', '3', '1',
                                                'B', '2', '2', '0', 'D', 'D',
                                                '5', 'D', '4', 'D', '3', 'D',
                                                '9', '9', '1', '2', '9', 'D',
                                                '1', '9', '3', 'C', '2', 'D',
                                                'B', '4', '4', '4', '4', '1',
                                                'E', '2', '0', '2', 'E', '4',
                                                '1', '3', 'E', '8', '2', '8',
                                                'B', 'D', '8', '2', 'B', 'D',
                                                '4', 'D', 'B', '7', '2', '6',
                                                'E', '5', 'A', 'F', 'B', 'C',
                                                'F', 'D', 'E', 'D', '9', '2',
                                                '5', 'C', 'B', '5', 'C', '3',
                                                '4', '9', 'E', '5', '6', '3',
                                                '3', '8', '6', 'B', '0', 'F',
                                                '0', '4', '1', '6', '0', '2',
                                                '0', 'C', '0', '1', '2', 'C',
                                                '9', '5', '5', '1', 'E', '5',
                                                '6', 'E', '9', '3', '7', '2',
                                                '6', '8', '1', '5', '2', '1',
                                                '1', '0', 'A', '7', 'D', 'E',
                                                '7', '2', '2', '5', 'E', '2',
                                                '8', 'B', '9', 'C', '9', '7',
                                                '1', 'C', '5', 'B', '3', 'A',
                                                'E', '9', '0', '4', '4', '0',
                                                'B', 'B', '0', 'E', '0', '0',
                                                'E', '5', 'B', '4', 'B', '2',
                                                'C', '6', '7', 'D', '3', '2',
                                                'F', '0', 'C', '5', '3', '2',
                                                '0', '6', '2', '4', 'C', '5',
                                                '0', 'C', 'F', 'C', '3', '3',
                                                '1', '1', '1', '7', 'B', 'F',
                                                'A', 'C', '7', '8', '9', 'F',
                                                'E', '6', 'C', 'A', 'F', '8',
                                                '4', 'D', 'B', '3', '3', 'A',
                                                'F', '8', '6', '1', '\0'};

const char *__MCC_OBR_matlabpath_data[] = {"OBR/", "work/",
                                           "toolbox/compiler/deploy/",
                                           "$TOOLBOXMATLABDIR/general/",
                                           "$TOOLBOXMATLABDIR/ops/",
                                           "$TOOLBOXMATLABDIR/lang/",
                                           "$TOOLBOXMATLABDIR/elmat/",
                                           "$TOOLBOXMATLABDIR/elfun/",
                                           "$TOOLBOXMATLABDIR/specfun/",
                                           "$TOOLBOXMATLABDIR/matfun/",
                                           "$TOOLBOXMATLABDIR/datafun/",
                                           "$TOOLBOXMATLABDIR/polyfun/",
                                           "$TOOLBOXMATLABDIR/funfun/",
                                           "$TOOLBOXMATLABDIR/sparfun/",
                                           "$TOOLBOXMATLABDIR/scribe/",
                                           "$TOOLBOXMATLABDIR/graph2d/",
                                           "$TOOLBOXMATLABDIR/graph3d/",
                                           "$TOOLBOXMATLABDIR/specgraph/",
                                           "$TOOLBOXMATLABDIR/graphics/",
                                           "$TOOLBOXMATLABDIR/uitools/",
                                           "$TOOLBOXMATLABDIR/strfun/",
                                           "$TOOLBOXMATLABDIR/imagesci/",
                                           "$TOOLBOXMATLABDIR/iofun/",
                                           "$TOOLBOXMATLABDIR/audiovideo/",
                                           "$TOOLBOXMATLABDIR/timefun/",
                                           "$TOOLBOXMATLABDIR/datatypes/",
                                           "$TOOLBOXMATLABDIR/verctrl/",
                                           "$TOOLBOXMATLABDIR/codetools/",
                                           "$TOOLBOXMATLABDIR/helptools/",
                                           "$TOOLBOXMATLABDIR/winfun/",
                                           "$TOOLBOXMATLABDIR/demos/",
                                           "toolbox/local/",
                                           "toolbox/stateflow/stateflow/",
                                           "toolbox/shared/hds/",
                                           "toolbox/compiler/",
                                           "toolbox/control/control/",
                                           "toolbox/control/ctrlguis/",
                                           "toolbox/control/ctrlobsolete/",
                                           "toolbox/control/ctrlutil/",
                                           "toolbox/shared/controllib/",
                                           "toolbox/shared/optimlib/",
                                           "toolbox/database/database/",
                                           "toolbox/ident/ident/",
                                           "toolbox/ident/idobsolete/",
                                           "toolbox/ident/idguis/",
                                           "toolbox/ident/idutils/",
                                           "toolbox/images/images/",
                                           "toolbox/images/imuitools/",
                                           "toolbox/images/iptutils/",
                                           "toolbox/mbc/mbc/",
                                           "toolbox/nnet/nnet/",
                                           "toolbox/nnet/nnutils/",
                                           "toolbox/optim/",
                                           "toolbox/robust/robust/",
                                           "toolbox/robust/rctutil/",
                                           "toolbox/robust/rctobsolete/robust/",
                                           "toolbox/robust/rctobsolete/lmi/",
                                           "toolbox/robust/rctobsolete/mutools/commands/",
                                           "toolbox/robust/rctobsolete/mutools/subs/",
                                           "toolbox/signal/signal/",
                                           "toolbox/signal/sigtools/",
                                           "toolbox/stats/",
                                           "toolbox/symbolic/"};
const int __MCC_OBR_matlabpath_data_count = 63;

const char *__MCC_OBR_classpath_data[] = {"java/jar/toolbox/control.jar",
                                          "java/jar/toolbox/database.jar"};
const int __MCC_OBR_classpath_data_count = 2;

const char *__MCC_OBR_mcr_application_options[] = { "" };
const int __MCC_OBR_mcr_application_option_count = 0;
const char *__MCC_OBR_mcr_runtime_options[] = { "" };
const int __MCC_OBR_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


